-- 코드를 입력하세요
SELECT 
YEAR(SALES_DATE) AS YEAR,
MONTH(SALES_DATE) AS MONTH,
GENDER,
COUNT(DISTINCT T2.USER_ID)AS USERS
FROM USER_INFO T1
JOIN ONLINE_SALE T2
ON T1.USER_ID = T2.USER_ID
GROUP BY YEAR, MONTH, GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER