-- 코드를 입력하세요
# SELECT 
# MONTH(START_DATE) MONTH, 
# CAR_ID, 
# COUNT(HISTORY_ID) RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY MONTH, CAR_ID
# HAVING SUM(RECORDS) >= 5 (SELECT SUM(RECORDS) 
#                           FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#                           GROUP BY CAR_ID)
# ORDER BY 1, 2 DESC

SELECT 
MONTH(START_DATE) AS MONTH, 
CAR_ID, 
COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
                 GROUP BY CAR_ID
                 HAVING COUNT(HISTORY_ID) >= 5)
                 AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, CAR_ID
ORDER BY 1, 2 DESC