# -- 코드를 입력하세요

SELECT
USER_ID, NICKNAME,
CONCAT(CITY,' ', STREET_ADDRESS1,' ',STREET_ADDRESS2) AS 전체주소,
CONCAT(LEFT(TLNO, 3), '-', MID(TLNO, 4, 4), '-', RIGHT(TLNO, 4)) AS 전화번호
FROM USED_GOODS_BOARD T1
JOIN USED_GOODS_USER T2
ON T1.WRITER_ID = T2.USER_ID
WHERE WRITER_ID IN
(SELECT WRITER_ID
 FROM USED_GOODS_BOARD
 GROUP BY WRITER_ID
 HAVING COUNT(BOARD_ID) >= 3)
 GROUP BY NICKNAME
ORDER BY 1 DESC


# CONCAT(CITY, STREET_ADDRESS1, STREET_ADDRESS2) AS 전체주소,
# CONCAT(SUBSTRING(컬럼명 from 1 for 3), '-' ,SUBSTRING(컬럼명 from 4 for 4), '-' ,SUBSTRING(컬럼명 from 8 for 4)) as PHN_NO
# concat(substr(GAME_START,1,2),':',substr(game_start,3,2))

# REGEXP_REPLACE(INT(TLNO), '(02|.{3})(.+)(.{4})', '\\1-\\2-\\3') AS 전화번호
