-- 코드를 입력하세요
SELECT 
USER_ID, 
NICKNAME,
SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD T1
JOIN USED_GOODS_USER T2
ON T1.WRITER_ID = T2.USER_ID
WHERE STATUS = "DONE"
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES

# WHERE USED_GOODS_BOARD.PRICE >= 700000
# WHERE TOTAL_SALES >= 700000 / T1.PRICE
#HAVING USED_GOODS_BOARD.PRICE >= 700000
#HAVING TOTAL_SALES >= 700000
# TOTAL_SALES  / STATUS = "DONE"

# SELECT 
# T2.USER_ID, 
# T2.NICKNAME,
# SUM(T1.PRICE) AS TOTAL_SALES
# FROM USED_GOODS_BOARD T1
# JOIN USED_GOODS_USER T2
# ON T1.WRITER_ID = T2.USER_ID
# GROUP BY USER_ID
# HAVING STATUS = "DONE"
# AND TOTAL_SALES >= 700000