-- 코드를 작성해주세요
select COUNT(a.ID) as FISH_COUNT, b.FISH_NAME
from FISH_INFO a 
join FISH_NAME_INFO b
on a.FISH_TYPE = b.FISH_TYPE
group by b.FISH_NAME
order by COUNT(ID) desc




# SELECT COUNT(a.ID) as FISH_COUNT, b.FISH_NAME
# FROM FISH_INFO a
# JOIN FISH_NAME_INFO b
# ON a.FISH_TYPE =  b.FISH_TYPE
# GROUP BY b.FISH_NAME
# ORDER BY FISH_COUNT DESC