-- 코드를 작성해주세요
# SELECT COUNT(ID) as FISH_COUNT, MONTH(TIME) as MONTH
# FROM FISH_INFO
# GROUP BY MONTH
# ORDER BY MONTH


select count(ID) as FISH_COUNT, month(TIME) as MONTH
from FISH_INFO
group by MONTH
order by MONTH